### ISSUE TITLE
Make MadGraph5_aMC-NLO image with LHAPDFs loaded on

### ISSUE THREAD

**Issue by matthewfeickert** [Neubauer-Group/bluewaters-docker-images#12]
As Blue Waters doesn't have external public internet support the various docker images that are being run can't download any additional files once they're on Blue Waters. This means that all required LHAPDF sets must be installed in the images.

```console
$ ssh BLUEWATERS
$ qsub -I -l gres=shifter -l nodes=1:ppn=8:xk -l walltime=01:00:00
INFO: Job submitted to account: bbdz
qsub: waiting for job 12255209.bw to start
qsub: job 12255209.bw ready

In Torque Shifter prologue batchID: 12255209
Number of nodes: 1
Starting munge and nscd service on compute nodes
uid=57956(feickert) gid=17389(ILL_bbdz) groups=1001(hpss_user),1000(ie_user),999(login_user),17389(ILL_bbdz)
Successfully started munge and nscd service on compute nodes
----------------------------------------
Begin Torque Prologue on nid25337
at Tue May 25 18:31:59 CDT 2021
Job Id:			12255209.bw
Username:		feickert
Group:			ILL_bbdz
Job name:		STDIN
Requested resources:	gres=shifter,nodes=1:ppn=8:xk,walltime=01:00:00,neednodes=1:ppn=8:xk
Queue:			normal
Account:		bbdz
End Torque Prologue:  11.447 elapsed
----------------------------------------
$ module load shifter
$ shifterimg pull scailfin/madgraph5-amc-nlo-centos:mg5_amc3.1.0
$ aprun -b -N 1 -- shifter --image=scailfin/madgraph5-amc-nlo-centos:mg5_amc3.1.0 -- /bin/bash -c 'lhapdf get NNPDF23_lo_as_0130_qed'
mount: warning: ufs seems to be mounted read-only.
mount: warning: dsl/opt seems to be mounted read-only.
PDF data file location not known: can't upgrade or install
Application 100550032 resources: utime ~0s, stime ~1s, Rss ~10240, inblocks ~58065, outblocks ~54210
```

This means that a `bluewaters-docker-images` version of https://github.com/scailfin/MadGraph5_aMC-NLO needs to be made that has multiple LHAPDF sets installed.

* Make a `mg5_amc/Dockerfile`
* Build it off of `scailfin/madgraph5-amc-nlo-centos:mg5_amc3.1.0`

```Dockerfile
ARG BASE_IMAGE=scailfin/madgraph5-amc-nlo-centos:mg5_amc3.1.0
FROM ${BASE_IMAGE} as base

RUN lhapdf get NNPDF23_lo_as_0130_qed && \
    lhapdf get ...
```

* Push up to Docker Hub as `neubauergroup/bluewaters-mg5_amc:3.1.0`

**Comment by matthewfeickert** [comment]
> As Blue Waters doesn't have external public internet support

@BenGalewsky just a sanity check: The above is correct, yes?

**Comment by matthewfeickert** [comment]
Okay, I now at least get

```console
$ ssh BLUEWATERS
$ qsub -I -l gres=shifter -l nodes=1:ppn=8:xk -l walltime=01:00:00
...
$ module load shifter
$ shifterimg pull neubauergroup/bluewaters-mg5_amc:3.1.0
# This fails as lhapdf tries to call out a query first
$ aprun -b -N 1 -- shifter --image=neubauergroup/bluewaters-mg5_amc:3.1.0 -- /bin/bash -c 'lhapdf get NNPDF23_lo_as_0130_qed'
mount: warning: ufs seems to be mounted read-only.
mount: warning: dsl/opt seems to be mounted read-only.
PDF data file location not known: can't upgrade or install
Application 100555477 resources: utime ~0s, stime ~1s, Rss ~42504, inblocks ~58065, outblocks ~54210
$ aprun -b -N 1 -- shifter --image=neubauergroup/bluewaters-mg5_amc:3.1.0 -- /bin/bash -c 'cd /usr/local/share/LHAPDF/ && ls -d */'
mount: warning: ufs seems to be mounted read-only.
mount: warning: dsl/opt seems to be mounted read-only.
NNPDF23_lo_as_0130_qed/
Application 100555604 resources: utime ~0s, stime ~1s, Rss ~42504, inblocks ~56772, outblocks ~54210
$ aprun -b -N 1 -- shifter --image=neubauergroup/bluewaters-mg5_amc:3.1.0 -- /bin/bash -c 'printf "generate p p > l+ l-\noutput drell-yan_output\nlaunch drell-yan_output\n" > drell-yan.mg5 && cat drell-yan.mg5 && mg5_aMC drell-yan.mg5'
mount: warning: ufs seems to be mounted read-only.
mount: warning: dsl/opt seems to be mounted read-only.
generate p p > l+ l-
output drell-yan_output
launch drell-yan_output
************************************************************
*                                                          *
*                     W E L C O M E to                     *
*              M A D G R A P H 5 _ a M C @ N L O           *
*                                                          *
*                                                          *
*                 *                       *                *
*                   *        * *        *                  *
*                     * * * * 5 * * * *                    *
*                   *        * *        *                  *
*                 *                       *                *
*                                                          *
*         VERSION 3.1.0                 2021-03-30         *
*                                                          *
*    The MadGraph5_aMC@NLO Development Team - Find us at   *
*    https://server06.fynu.ucl.ac.be/projects/madgraph     *
*                            and                           *
*            http://amcatnlo.web.cern.ch/amcatnlo/         *
*                                                          *
*               Type 'help' for in-line help.              *
*           Type 'tutorial' to learn how MG5 works         *
*    Type 'tutorial aMCatNLO' to learn how aMC@NLO works   *
*    Type 'tutorial MadLoop' to learn how MadLoop works    *
*                                                          *
************************************************************
Traceback (most recent call last):
  File "/usr/local/MG5_aMC/bin/mg5_aMC", line 176, in <module>
    cmd_line = interface.MasterCmd(mgme_dir = options.mgme_dir)
  File "/usr/local/MG5_aMC/madgraph/interface/master_interface.py", line 612, in __init__
    self.cmd.__init__(self, *args, **opt)     
  File "/usr/local/MG5_aMC/madgraph/interface/madgraph_interface.py", line 3053, in __init__
    shutil.copy(make_opts_source, make_opts)
  File "/usr/local/lib/python3.8/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
OSError: [Errno 30] Read-only file system: '/usr/local/MG5_aMC/Template/LO/Source/make_opts'
Application 100555662 resources: utime ~4s, stime ~1s, Rss ~43872, inblocks ~74632, outblocks ~54214
```

So there's an error to go off of now for the feasibility of using Blue Waters for MadGraph simulation production.
