### ISSUE TITLE
Blue Waters Read-only file system causing MadGraph5 execution to fail

### ISSUE THREAD

**Issue by matthewfeickert** [Neubauer-Group/bluewaters-docker-images#14]
Okay, I now at least get

```console
$ ssh BLUEWATERS
$ qsub -I -l gres=shifter -l nodes=1:ppn=8:xk -l walltime=01:00:00
...
$ module load shifter
$ shifterimg pull neubauergroup/bluewaters-mg5_amc:3.1.0
# This fails as lhapdf tries to call out a query first
$ aprun -b -N 1 -- shifter --image=neubauergroup/bluewaters-mg5_amc:3.1.0 -- /bin/bash -c 'lhapdf get NNPDF23_lo_as_0130_qed'
mount: warning: ufs seems to be mounted read-only.
mount: warning: dsl/opt seems to be mounted read-only.
PDF data file location not known: can't upgrade or install
Application 100555477 resources: utime ~0s, stime ~1s, Rss ~42504, inblocks ~58065, outblocks ~54210
$ aprun -b -N 1 -- shifter --image=neubauergroup/bluewaters-mg5_amc:3.1.0 -- /bin/bash -c 'cd /usr/local/share/LHAPDF/ && ls -d */'
mount: warning: ufs seems to be mounted read-only.
mount: warning: dsl/opt seems to be mounted read-only.
NNPDF23_lo_as_0130_qed/
Application 100555604 resources: utime ~0s, stime ~1s, Rss ~42504, inblocks ~56772, outblocks ~54210
$ aprun -b -N 1 -- shifter --image=neubauergroup/bluewaters-mg5_amc:3.1.0 -- /bin/bash -c 'printf "generate p p > l+ l-\noutput drell-yan_output\nlaunch drell-yan_output\n" > drell-yan.mg5 && cat drell-yan.mg5 && mg5_aMC drell-yan.mg5'
mount: warning: ufs seems to be mounted read-only.
mount: warning: dsl/opt seems to be mounted read-only.
generate p p > l+ l-
output drell-yan_output
launch drell-yan_output
************************************************************
*                                                          *
*                     W E L C O M E to                     *
*              M A D G R A P H 5 _ a M C @ N L O           *
*                                                          *
*                                                          *
*                 *                       *                *
*                   *        * *        *                  *
*                     * * * * 5 * * * *                    *
*                   *        * *        *                  *
*                 *                       *                *
*                                                          *
*         VERSION 3.1.0                 2021-03-30         *
*                                                          *
*    The MadGraph5_aMC@NLO Development Team - Find us at   *
*    https://server06.fynu.ucl.ac.be/projects/madgraph     *
*                            and                           *
*            http://amcatnlo.web.cern.ch/amcatnlo/         *
*                                                          *
*               Type 'help' for in-line help.              *
*           Type 'tutorial' to learn how MG5 works         *
*    Type 'tutorial aMCatNLO' to learn how aMC@NLO works   *
*    Type 'tutorial MadLoop' to learn how MadLoop works    *
*                                                          *
************************************************************
Traceback (most recent call last):
  File "/usr/local/MG5_aMC/bin/mg5_aMC", line 176, in <module>
    cmd_line = interface.MasterCmd(mgme_dir = options.mgme_dir)
  File "/usr/local/MG5_aMC/madgraph/interface/master_interface.py", line 612, in __init__
    self.cmd.__init__(self, *args, **opt)     
  File "/usr/local/MG5_aMC/madgraph/interface/madgraph_interface.py", line 3053, in __init__
    shutil.copy(make_opts_source, make_opts)
  File "/usr/local/lib/python3.8/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
OSError: [Errno 30] Read-only file system: '/usr/local/MG5_aMC/Template/LO/Source/make_opts'
Application 100555662 resources: utime ~4s, stime ~1s, Rss ~43872, inblocks ~74632, outblocks ~54214
```

So there's an error to go off of now for the feasibility of using Blue Waters for MadGraph simulation production.

_Originally posted by @matthewfeickert in https://github.com/Neubauer-Group/bluewaters-docker-images/issues/12#issuecomment-848436961_

**Comment by matthewfeickert** [comment]
This is failing right out of the gate with the first `generate` command too

```console
$ aprun -b -N 1 -- shifter --image=neubauergroup/bluewaters-mg5_amc:3.1.0 -- /bin/bash -c 'printf "generate p p > l+ l-\n" > test.mg5 && cat test.mg5 && mg5_aMC test.mg5'
mount: warning: ufs seems to be mounted read-only.
mount: warning: dsl/opt seems to be mounted read-only.
generate p p > l+ l-
************************************************************
*                                                          *
*                     W E L C O M E to                     *
*              M A D G R A P H 5 _ a M C @ N L O           *
*                                                          *
*                                                          *
*                 *                       *                *
*                   *        * *        *                  *
*                     * * * * 5 * * * *                    *
*                   *        * *        *                  *
*                 *                       *                *
*                                                          *
*         VERSION 3.1.0                 2021-03-30         *
*                                                          *
*    The MadGraph5_aMC@NLO Development Team - Find us at   *
*    https://server06.fynu.ucl.ac.be/projects/madgraph     *
*                            and                           *
*            http://amcatnlo.web.cern.ch/amcatnlo/         *
*                                                          *
*               Type 'help' for in-line help.              *
*           Type 'tutorial' to learn how MG5 works         *
*    Type 'tutorial aMCatNLO' to learn how aMC@NLO works   *
*    Type 'tutorial MadLoop' to learn how MadLoop works    *
*                                                          *
************************************************************
Traceback (most recent call last):
  File "/usr/local/MG5_aMC/bin/mg5_aMC", line 176, in <module>
    cmd_line = interface.MasterCmd(mgme_dir = options.mgme_dir)
  File "/usr/local/MG5_aMC/madgraph/interface/master_interface.py", line 612, in __init__
    self.cmd.__init__(self, *args, **opt)     
  File "/usr/local/MG5_aMC/madgraph/interface/madgraph_interface.py", line 3053, in __init__
    shutil.copy(make_opts_source, make_opts)
  File "/usr/local/lib/python3.8/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
OSError: [Errno 30] Read-only file system: '/usr/local/MG5_aMC/Template/LO/Source/make_opts'
Application 100555718 resources: utime ~4s, stime ~1s, Rss ~43680, inblocks ~74631, outblocks ~54214
```

and actually is failing just at MadGraph's invocation

```console
$ aprun -b -N 1 -- shifter --image=neubauergroup/bluewaters-mg5_amc:3.1.0 -- /bin/bash -I
mount: warning: ufs seems to be mounted read-only.
mount: warning: dsl/opt seems to be mounted read-only.
mg5_aMC
************************************************************
*                                                          *
*                     W E L C O M E to                     *
*              M A D G R A P H 5 _ a M C @ N L O           *
*                                                          *
*                                                          *
*                 *                       *                *
*                   *        * *        *                  *
*                     * * * * 5 * * * *                    *
*                   *        * *        *                  *
*                 *                       *                *
*                                                          *
*         VERSION 3.1.0                 2021-03-30         *
*                                                          *
*    The MadGraph5_aMC@NLO Development Team - Find us at   *
*    https://server06.fynu.ucl.ac.be/projects/madgraph     *
*                            and                           *
*            http://amcatnlo.web.cern.ch/amcatnlo/         *
*                                                          *
*               Type 'help' for in-line help.              *
*           Type 'tutorial' to learn how MG5 works         *
*    Type 'tutorial aMCatNLO' to learn how aMC@NLO works   *
*    Type 'tutorial MadLoop' to learn how MadLoop works    *
*                                                          *
************************************************************
Traceback (most recent call last):
  File "/usr/local/MG5_aMC/bin/mg5_aMC", line 176, in <module>
    cmd_line = interface.MasterCmd(mgme_dir = options.mgme_dir)
  File "/usr/local/MG5_aMC/madgraph/interface/master_interface.py", line 612, in __init__
    self.cmd.__init__(self, *args, **opt)     
  File "/usr/local/MG5_aMC/madgraph/interface/madgraph_interface.py", line 3053, in __init__
    shutil.copy(make_opts_source, make_opts)
  File "/usr/local/lib/python3.8/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
OSError: [Errno 30] Read-only file system: '/usr/local/MG5_aMC/Template/LO/Source/make_opts'
```

Locally this sort of behavior is fine in the Docker image

<details>
<summary>Example output:</summary>

```console
$ docker run --rm neubauergroup/bluewaters-mg5_amc:3.1.0 'echo "generate p p > l+ l-" >> test.mg5 && mg5_aMC test.mg5'
************************************************************
*                                                          *
*                     W E L C O M E to                     *
*              M A D G R A P H 5 _ a M C @ N L O           *
*                                                          *
*                                                          *
*                 *                       *                *
*                   *        * *        *                  *
*                     * * * * 5 * * * *                    *
*                   *        * *        *                  *
*                 *                       *                *
*                                                          *
*         VERSION 3.1.0                 2021-03-30         *
*                                                          *
*    The MadGraph5_aMC@NLO Development Team - Find us at   *
*    https://server06.fynu.ucl.ac.be/projects/madgraph     *
*                            and                           *
*            http://amcatnlo.web.cern.ch/amcatnlo/         *
*                                                          *
*               Type 'help' for in-line help.              *
*           Type 'tutorial' to learn how MG5 works         *
*    Type 'tutorial aMCatNLO' to learn how aMC@NLO works   *
*    Type 'tutorial MadLoop' to learn how MadLoop works    *
*                                                          *
************************************************************
load MG5 configuration from ../../../usr/local/MG5_aMC/input/mg5_configuration.txt 
set fastjet to fastjet-config
set lhapdf to lhapdf-config
set lhapdf to lhapdf-config
Using default text editor "vi". Set another one in ./input/mg5_configuration.txt
No valid eps viewer found. Please set in ./input/mg5_configuration.txt
No valid web browser found. Please set in ./input/mg5_configuration.txt
import /home/docker/data/test.mg5
The import format was not given, so we guess it as command
generate p p > l+ l-
No model currently active, so we import the Standard Model
INFO: load particles 
INFO: load vertices 
INFO: Restrict model sm with file ../../../usr/local/MG5_aMC/models/sm/restrict_default.dat . 
INFO: Run "set stdout_level DEBUG" before import for more information. 
INFO: Change particles name to pass to MG5 convention 
Defined multiparticle p = g u c d s u~ c~ d~ s~
Defined multiparticle j = g u c d s u~ c~ d~ s~
Defined multiparticle l+ = e+ mu+
Defined multiparticle l- = e- mu-
Defined multiparticle vl = ve vm vt
Defined multiparticle vl~ = ve~ vm~ vt~
Defined multiparticle all = g u c d s u~ c~ d~ s~ a ve vm vt e- mu- ve~ vm~ vt~ e+ mu+ t b t~ b~ z w+ h w- ta- ta+
INFO: Checking for minimal orders which gives processes. 
INFO: Please specify coupling orders to bypass this step. 
INFO: Trying process: g g > e+ e- WEIGHTED<=4 @1  
INFO: Trying process: g g > e+ mu- WEIGHTED<=4 @1  
INFO: Trying process: g g > mu+ e- WEIGHTED<=4 @1  
INFO: Trying process: g g > mu+ mu- WEIGHTED<=4 @1  
INFO: Trying process: u u~ > e+ e- WEIGHTED<=4 @1  
INFO: Process has 2 diagrams 
INFO: Trying process: u u~ > e+ mu- WEIGHTED<=4 @1  
INFO: Trying process: u u~ > mu+ e- WEIGHTED<=4 @1  
INFO: Trying process: u u~ > mu+ mu- WEIGHTED<=4 @1  
INFO: Process has 2 diagrams 
INFO: Trying process: u c~ > e+ e- WEIGHTED<=4 @1  
INFO: Trying process: u c~ > e+ mu- WEIGHTED<=4 @1  
INFO: Trying process: u c~ > mu+ e- WEIGHTED<=4 @1  
INFO: Trying process: u c~ > mu+ mu- WEIGHTED<=4 @1  
INFO: Trying process: c u~ > e+ e- WEIGHTED<=4 @1  
INFO: Trying process: c u~ > e+ mu- WEIGHTED<=4 @1  
INFO: Trying process: c u~ > mu+ e- WEIGHTED<=4 @1  
INFO: Trying process: c u~ > mu+ mu- WEIGHTED<=4 @1  
INFO: Trying process: c c~ > e+ e- WEIGHTED<=4 @1  
INFO: Process has 2 diagrams 
INFO: Trying process: c c~ > e+ mu- WEIGHTED<=4 @1  
INFO: Trying process: c c~ > mu+ e- WEIGHTED<=4 @1  
INFO: Trying process: c c~ > mu+ mu- WEIGHTED<=4 @1  
INFO: Process has 2 diagrams 
INFO: Trying process: d d~ > e+ e- WEIGHTED<=4 @1  
INFO: Process has 2 diagrams 
INFO: Trying process: d d~ > e+ mu- WEIGHTED<=4 @1  
INFO: Trying process: d d~ > mu+ e- WEIGHTED<=4 @1  
INFO: Trying process: d d~ > mu+ mu- WEIGHTED<=4 @1  
INFO: Process has 2 diagrams 
INFO: Trying process: d s~ > e+ e- WEIGHTED<=4 @1  
INFO: Trying process: d s~ > e+ mu- WEIGHTED<=4 @1  
INFO: Trying process: d s~ > mu+ e- WEIGHTED<=4 @1  
INFO: Trying process: d s~ > mu+ mu- WEIGHTED<=4 @1  
INFO: Trying process: s d~ > e+ e- WEIGHTED<=4 @1  
INFO: Trying process: s d~ > e+ mu- WEIGHTED<=4 @1  
INFO: Trying process: s d~ > mu+ e- WEIGHTED<=4 @1  
INFO: Trying process: s d~ > mu+ mu- WEIGHTED<=4 @1  
INFO: Trying process: s s~ > e+ e- WEIGHTED<=4 @1  
INFO: Process has 2 diagrams 
INFO: Trying process: s s~ > e+ mu- WEIGHTED<=4 @1  
INFO: Trying process: s s~ > mu+ e- WEIGHTED<=4 @1  
INFO: Trying process: s s~ > mu+ mu- WEIGHTED<=4 @1  
INFO: Process has 2 diagrams 
INFO: Process u~ u > e+ e- added to mirror process u u~ > e+ e- 
INFO: Process u~ u > mu+ mu- added to mirror process u u~ > mu+ mu- 
INFO: Process c~ c > e+ e- added to mirror process c c~ > e+ e- 
INFO: Process c~ c > mu+ mu- added to mirror process c c~ > mu+ mu- 
INFO: Process d~ d > e+ e- added to mirror process d d~ > e+ e- 
INFO: Process d~ d > mu+ mu- added to mirror process d d~ > mu+ mu- 
INFO: Process s~ s > e+ e- added to mirror process s s~ > e+ e- 
INFO: Process s~ s > mu+ mu- added to mirror process s s~ > mu+ mu- 
8 processes with 16 diagrams generated in 0.181 s
Total: 8 processes with 16 diagrams
quit
```

</details>

**Comment by matthewfeickert** [comment]
Following the [Shifter "Mapping directoties"](https://bluewaters.ncsa.illinois.edu/shifter#mapping-directories) docs the following will at least mount the image correclty

```console
$ qsub -I -l gres=shifter -l nodes=1:ppn=8:xk -l walltime=01:00:00
$ module load shifter
$ shifterimg pull neubauergroup/bluewaters-mg5_amc:3.1.0
$ aprun -b -N 1 -- shifter --clearenv --image=neubauergroup/bluewaters-mg5_amc:3.1.0 --volume=/mnt/a/u/sciteam/$USER:/mnt/a/u/sciteam/$USER -- /bin/bash -I
```

though trying to run MadGraph still fails

```console
$ aprun -b -N 1 -- shifter --clearenv --image=neubauergroup/bluewaters-mg5_amc:3.1.0 --volume=/mnt/a/u/sciteam/$USER:/mnt/a/u/sciteam/$USER -- /bin/bash -I
mount: warning: ufs seems to be mounted read-only.
mount: warning: dsl/opt seems to be mounted read-only.

mg5_aMC
************************************************************
*                                                          *
*                     W E L C O M E to                     *
*              M A D G R A P H 5 _ a M C @ N L O           *
*                                                          *
*                                                          *
*                 *                       *                *
*                   *        * *        *                  *
*                     * * * * 5 * * * *                    *
*                   *        * *        *                  *
*                 *                       *                *
*                                                          *
*         VERSION 3.1.0                 2021-03-30         *
*                                                          *
*    The MadGraph5_aMC@NLO Development Team - Find us at   *
*    https://server06.fynu.ucl.ac.be/projects/madgraph     *
*                            and                           *
*            http://amcatnlo.web.cern.ch/amcatnlo/         *
*                                                          *
*               Type 'help' for in-line help.              *
*           Type 'tutorial' to learn how MG5 works         *
*    Type 'tutorial aMCatNLO' to learn how aMC@NLO works   *
*    Type 'tutorial MadLoop' to learn how MadLoop works    *
*                                                          *
************************************************************
Traceback (most recent call last):
  File "/usr/local/MG5_aMC/bin/mg5_aMC", line 176, in <module>
    cmd_line = interface.MasterCmd(mgme_dir = options.mgme_dir)
  File "/usr/local/MG5_aMC/madgraph/interface/master_interface.py", line 612, in __init__
    self.cmd.__init__(self, *args, **opt)     
  File "/usr/local/MG5_aMC/madgraph/interface/madgraph_interface.py", line 3053, in __init__
    shutil.copy(make_opts_source, make_opts)
  File "/usr/local/lib/python3.8/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
OSError: [Errno 30] Read-only file system: '/usr/local/MG5_aMC/Template/LO/Source/make_opts'
```

---

Note that here the [`--clearenv` `shifter` option](https://bluewaters.ncsa.illinois.edu/shifter#shifter-command) is being used where

> `-E`/`--clearenv`: Don't pass environment of the MOM nodes to the compute nodes. Recommended.

**Comment by matthewfeickert** [comment]
The `aprun` command is getting too long, so I am now using a shell script that only runs it

```console
$ cat aprun_command.sh
```
```bash
#!/bin/bash

aprun -b -N 1 -cc none \
  -- shifter \
    --clearenv \
    --image=neubauergroup/bluewaters-mg5_amc:3.1.0 \
    --volume=/mnt/a/u/sciteam/"${USER}"/user_scratch:/home/docker/data \
    --volume=/mnt/a/u/sciteam/"${USER}":/mnt/a/u/sciteam/"${USER}" \
    --workdir=/home/docker/data \
    -- /bin/bash -I
```

**Comment by matthewfeickert** [comment]
With the new image from PR #16 pulled the following works

```console
$ ls run_control/
drell-yan.mg5
$ . aprun_command.sh
> mg5_aMC /mnt/a/u/sciteam/feickert/run_control/drell-yan.mg5
...
INFO: Combining runs 
sum of cpu time of last step: 1m45s
INFO: finish refine 
refine 10000 --treshold=0.9
No need for second refine due to stability of cross-section
INFO: Combining Events 
  === Results Summary for run: run_01 tag: tag_1 ===

     Cross-section :   1678 +- 5.179 pb
     Nb of events :  10000
 
INFO: Running Systematics computation 
INFO:  Idle: 1,  Running: 3,  Completed: 0 [ current time: 08h00 ] 
INFO:  Idle: 0,  Running: 3,  Completed: 1 [  38.3s  ] 
INFO: # events generated with PDF: NNPDF23_lo_as_0130_qed (247000) 
INFO: #Will Compute 145 weights per event. 
INFO: #***************************************************************************
#
# original cross-section: 1677.706738304647
#     scale variation: +16.1% -16.3%
#     central scheme variation: +1.43e-09% -20.7%
# PDF variation: +3.07% -3.07%
#
# dynamical scheme # 1 : 1604.91 +17% -17.1% # \sum ET
# dynamical scheme # 2 : 1604.91 +17% -17.1% # \sum\sqrt{m^2+pt^2}
# dynamical scheme # 3 : 1329.81 +20.7% -20.3% # 0.5 \sum\sqrt{m^2+pt^2}
# dynamical scheme # 4 : 1677.71 +16.1% -16.3% # \sqrt{\hat s}
#***************************************************************************
 
INFO: End of systematics computation 
store_events
INFO: Storing parton level results 
INFO: End Parton 
reweight -from_cards
decay_events -from_cards
INFO: storing files of previous run 
INFO: Done 
quit
INFO:  
more information in /home/docker/data/drell-yan_output/index.html
quit
> ls -l drell-yan_output
total 2676
drwxr-xr-x 3 feickert ILL_bbdz    4096 May 26 05:53 bin
drwxr-xr-x 2 feickert ILL_bbdz    4096 May 27 07:52 Cards
-rw-r--r-- 1 feickert ILL_bbdz    2071 May 27 07:54 crossx.html
drwxr-xr-x 3 feickert ILL_bbdz    4096 May 27 07:53 Events
drwxr-xr-x 3 feickert ILL_bbdz    4096 May 27 07:54 HTML
-rw-r--r-- 1 feickert ILL_bbdz    1964 May 27 07:54 index.html
drwxr-xr-x 3 feickert ILL_bbdz    4096 May 27 07:52 lib
-rw-r--r-- 1 feickert ILL_bbdz 2678284 May 27 07:52 madevent.tar.gz
-rw-r--r-- 1 feickert ILL_bbdz       5 May 27 07:52 MGMEVersion.txt
-rw-r--r-- 1 feickert ILL_bbdz    6747 Mar 29 21:50 README
-rw-r--r-- 1 feickert ILL_bbdz    5371 Mar 29 21:50 README.systematics
drwxr-xr-x 7 feickert ILL_bbdz    4096 May 27 07:52 Source
drwxr-xr-x 3 feickert ILL_bbdz    4096 May 27 07:53 SubProcesses
-rw-r--r-- 1 feickert ILL_bbdz       6 Mar 29 21:50 TemplateVersion.txt
> exit
$ ls user_scratch/drell-yan_output/
Cards  Events  HTML  MGMEVersion.txt  README  README.systematics  Source  SubProcesses  TemplateVersion.txt  bin  crossx.html  index.html  lib  madevent.tar.gz
```

--- 

(on local machine, using development some code APIs that aren't publicly released at the moment)

```console
$ scp BLUEWATERS:/mnt/a/u/sciteam/feickert/user_scratch/drell-yan_output/Events/run_01/unweighted_events.lhe.gz /tmp/
$ cat awkward_example.py
```
```python
from pathlib import Path

import awkward as ak
import hist
import pylhe

if __name__ == "__main__":
    pylhe.register_awkward()
    lhe_filepath = Path("/tmp").joinpath("unweighted_events.lhe.gz")
    arr = pylhe.to_awkward(pylhe.read_lhe_with_attributes(lhe_filepath))

    hist1 = hist.Hist.new.Reg(100, 50, 150).Int64()
    hist1.fill((arr.particles.vector[:, -1] + arr.particles.vector[:, -2]).mass)

    artists = hist1.plot1d()
    ax = artists[0].stairs.axes
    ax.set_yscale("log")
    ax.set_xlabel("Mass [GeV]")
    ax.set_ylabel("Count")

    fig = ax.get_figure()
    fig.savefig("drell-yan.png")
```
```console
$ python awkward_example.py
```

![drell-yan](https://user-images.githubusercontent.com/5142394/119792064-02bbc300-be9b-11eb-99c4-576e529cf9bc.png)


---

Modest progress :+1:

@msneubauer @BenGalewsky now to scale this up and out.
